version: "3"
services:
  web:
    build: .
    ports:
      - 80:8080
    restart: always
  devicecontrol:
    image: www.spoohapps.com/devicecontrol-rpi
    ports:
      - 8080:8080
    volumes:
      - ./conf/devicecontrol/devicecontrol.conf:/opt/devicecontrol/devicecontrol.conf
      - ./conf/profile.conf:/opt/devicecontrol/profile/profile.conf
      - ./conf/rabbitmq/client:/root/devicecontrol
      - ./conf/devicecontrol/auth/server:/root/devicecontrolauth
      - ./conf/data/devicecontrol/oauth:/root/oauth
      - ./conf/data/jble6lowpand:/opt/jble6lowpand/data
    restart: always
  scanner:
    image: www.spoohapps.com/jble6lowpand
    volumes:
    - ./conf/jble6lowpand/jble6lowpand.conf:/opt/jble6lowpand/jble6lowpand.conf
    - ./conf/data/jble6lowpand:/opt/jble6lowpand/data
    - /sys/kernel/debug/bluetooth/6lowpan_control:/opt/jble6lowpand/bin/6lowpan_control
    network_mode: host
    privileged: true
    restart: always
  shovel:
    image: www.spoohapps.com/jble6lowpanshoveld-rpi
    ports:
      - 8081:8080
    volumes:
      - ./conf/jble6lowpanshoveld/jble6lowpanshoveld.conf:/opt/jble6lowpanshoveld/jble6lowpanshoveld.conf
      - ./conf/profile.conf:/root/jble6lowpanshoveld/profile.conf
      - ./conf/rabbitmq/client:/root/jble6lowpanshoveld/client
    restart: always
  rabbitmq:
    image: www.spoohapps.com/rabbitmq-rpi
    ports:
      - 15672:15672
      - 5671:5671
      - 1883:1883
    volumes:
      - ./conf/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./conf/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./conf/rabbitmq/server/cacert.pem:/etc/rabbitmq/cacert.pem
      - ./conf/rabbitmq/server/cert.pem:/etc/rabbitmq/cert.pem
      - ./conf/rabbitmq/server/key.pem:/etc/rabbitmq/key.pem
      - ./conf/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./conf/rabbitmq/auth/client:/etc/rabbitmq/auth
      - ./conf/data/rabbitmq:/var/lib/rabbitmq
    restart: always
  couchdb:
    image: treehouses/couchdb
    ports:
    - 5984:5984
    volumes:
    - ./conf/data/couchdb:/opt/couchdb/data
    restart: always
  redis:
    image: redis:5
    ports:
    - 6379:6379
    - 16379:16379
    volumes:
    - ./conf/data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always
